/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthWheelsImport } from './routes/_auth/wheels'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthWheelsIndexImport } from './routes/_auth/wheels/index'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthWheelsRoute = AuthWheelsImport.update({
  path: '/wheels',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthWheelsIndexRoute = AuthWheelsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthWheelsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/wheels': {
      id: '/_auth/wheels'
      path: '/wheels'
      fullPath: '/wheels'
      preLoaderRoute: typeof AuthWheelsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/wheels/': {
      id: '/_auth/wheels/'
      path: '/'
      fullPath: '/wheels/'
      preLoaderRoute: typeof AuthWheelsIndexImport
      parentRoute: typeof AuthWheelsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthDashboardRoute,
    AuthWheelsRoute: AuthWheelsRoute.addChildren({ AuthWheelsIndexRoute }),
  }),
  LoginRoute,
  LogoutRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/logout"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/wheels"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/wheels": {
      "filePath": "_auth/wheels.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/wheels/"
      ]
    },
    "/_auth/wheels/": {
      "filePath": "_auth/wheels/index.tsx",
      "parent": "/_auth/wheels"
    }
  }
}
ROUTE_MANIFEST_END */
